[package]
name = "renderer"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
cef = { path = "../cef" }
cef-sys = { path = "../cef-sys" }
winapi = { version = "0.3.8", features = ["libloaderapi", "winuser", "wincon"] }
