[package]
name = "loader"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libloading = "0.5.2"
winapi = { version = "0.3.8", features = ["winbase"] }